const adjectives = [
  'able',
  'above',
  'absent',
  'absolute',
  'abstract',
  'abundant',
  'academic',
  'acceptable',
  'accepted',
  'accessible',
  'accurate',
  'accused',
  'active',
  'actual',
  'acute',
  'added',
  'additional',
  'adequate',
  'adjacent',
  'administrative',
  'adorable',
  'advanced',
  'adverse',
  'advisory',
  'aesthetic',
  'afraid',
  'african',
  'aggregate',
  'aggressive',
  'agreeable',
  'agreed',
  'agricultural',
  'alert',
  'alive',
  'alleged',
  'allied',
  'alone',
  'alright',
  'alternative',
  'amateur',
  'amazing',
  'ambitious',
  'american',
  'amused',
  'ancient',
  'angry',
  'annoyed',
  'annual',
  'anonymous',
  'anxious',
  'appalling',
  'apparent',
  'applicable',
  'appropriate',
  'arab',
  'arbitrary',
  'architectural',
  'armed',
  'arrogant',
  'artificial',
  'artistic',
  'ashamed',
  'asian',
  'asleep',
  'assistant',
  'associated',
  'atomic',
  'attractive',
  'australian',
  'automatic',
  'autonomous',
  'available',
  'average',
  'awake',
  'aware',
  'awful',
  'awkward',
  'back',
  'bad',
  'balanced',
  'bare',
  'basic',
  'beautiful',
  'beneficial',
  'better',
  'bewildered',
  'big',
  'binding',
  'biological',
  'bitter',
  'bizarre',
  'black',
  'blank',
  'blind',
  'blonde',
  'bloody',
  'blue',
  'blushing',
  'boiling',
  'bold',
  'bored',
  'boring',
  'bottom',
  'brainy',
  'brave',
  'breakable',
  'breezy',
  'brief',
  'bright',
  'brilliant',
  'british',
  'broad',
  'broken',
  'brown',
  'bumpy',
  'burning',
  'busy',
  'calm',
  'canadian',
  'capable',
  'capitalist',
  'careful',
  'casual',
  'catholic',
  'causal',
  'cautious',
  'central',
  'certain',
  'changing',
  'characteristic',
  'charming',
  'cheap',
  'cheerful',
  'chemical',
  'chief',
  'chilly',
  'chinese',
  'chosen',
  'christian',
  'chronic',
  'chubby',
  'circular',
  'civic',
  'civil',
  'civilian',
  'classic',
  'classical',
  'clean',
  'clear',
  'clever',
  'clinical',
  'close',
  'closed',
  'cloudy',
  'clumsy',
  'coastal',
  'cognitive',
  'coherent',
  'cold',
  'collective',
  'colonial',
  'colorful',
  'colossal',
  'coloured',
  'colourful',
  'combative',
  'combined',
  'comfortable',
  'coming',
  'commercial',
  'common',
  'communist',
  'compact',
  'comparable',
  'comparative',
  'compatible',
  'competent',
  'competitive',
  'complete',
  'complex',
  'complicated',
  'comprehensive',
  'compulsory',
  'conceptual',
  'concerned',
  'concrete',
  'condemned',
  'confident',
  'confidential',
  'confused',
  'conscious',
  'conservation',
  'conservative',
  'considerable',
  'consistent',
  'constant',
  'constitutional',
  'contemporary',
  'content',
  'continental',
  'continued',
  'continuing',
  'continuous',
  'controlled',
  'controversial',
  'convenient',
  'conventional',
  'convinced',
  'convincing',
  'cooing',
  'cool',
  'cooperative',
  'corporate',
  'correct',
  'corresponding',
  'costly',
  'courageous',
  'crazy',
  'creative',
  'creepy',
  'criminal',
  'critical',
  'crooked',
  'crowded',
  'crucial',
  'crude',
  'cruel',
  'cuddly',
  'cultural',
  'curious',
  'curly',
  'current',
  'curved',
  'cute',
  'daily',
  'damaged',
  'damp',
  'dangerous',
  'dark',
  'dead',
  'deaf',
  'deafening',
  'dear',
  'decent',
  'decisive',
  'deep',
  'defeated',
  'defensive',
  'defiant',
  'definite',
  'deliberate',
  'delicate',
  'delicious',
  'delighted',
  'delightful',
  'democratic',
  'dependent',
  'depressed',
  'desirable',
  'desperate',
  'detailed',
  'determined',
  'developed',
  'developing',
  'devoted',
  'different',
  'difficult',
  'digital',
  'diplomatic',
  'direct',
  'dirty',
  'disabled',
  'disappointed',
  'disastrous',
  'disciplinary',
  'disgusted',
  'distant',
  'distinct',
  'distinctive',
  'distinguished',
  'disturbed',
  'disturbing',
  'diverse',
  'divine',
  'dizzy',
  'domestic',
  'dominant',
  'double',
  'doubtful',
  'drab',
  'dramatic',
  'dreadful',
  'driving',
  'drunk',
  'dry',
  'dual',
  'due',
  'dull',
  'dusty',
  'dutch',
  'dying',
  'dynamic',
  'eager',
  'early',
  'eastern',
  'easy',
  'economic',
  'educational',
  'eerie',
  'effective',
  'efficient',
  'elaborate',
  'elated',
  'elderly',
  'eldest',
  'electoral',
  'electric',
  'electrical',
  'electronic',
  'elegant',
  'eligible',
  'embarrassed',
  'embarrassing',
  'emotional',
  'empirical',
  'empty',
  'enchanting',
  'encouraging',
  'endless',
  'energetic',
  'english',
  'enormous',
  'enthusiastic',
  'entire',
  'entitled',
  'envious',
  'environmental',
  'equal',
  'equivalent',
  'essential',
  'established',
  'estimated',
  'ethical',
  'ethnic',
  'european',
  'eventual',
  'everyday',
  'evident',
  'evil',
  'evolutionary',
  'exact',
  'excellent',
  'exceptional',
  'excess',
  'excessive',
  'excited',
  'exciting',
  'exclusive',
  'existing',
  'exotic',
  'expected',
  'expensive',
  'experienced',
  'experimental',
  'explicit',
  'extended',
  'extensive',
  'external',
  'extra',
  'extraordinary',
  'extreme',
  'exuberant',
  'faint',
  'fair',
  'faithful',
  'familiar',
  'famous',
  'fancy',
  'fantastic',
  'far',
  'fascinating',
  'fashionable',
  'fast',
  'fat',
  'fatal',
  'favourable',
  'favourite',
  'federal',
  'fellow',
  'female',
  'feminist',
  'few',
  'fierce',
  'filthy',
  'final',
  'financial',
  'fine',
  'firm',
  'fiscal',
  'fit',
  'fixed',
  'flaky',
  'flat',
  'flexible',
  'fluffy',
  'fluttering',
  'flying',
  'following',
  'fond',
  'foolish',
  'foreign',
  'formal',
  'formidable',
  'forthcoming',
  'fortunate',
  'forward',
  'fragile',
  'frail',
  'frantic',
  'free',
  'french',
  'frequent',
  'fresh',
  'friendly',
  'frightened',
  'front',
  'frozen',
  'fucking',
  'full',
  'full-time',
  'fun',
  'functional',
  'fundamental',
  'funny',
  'furious',
  'future',
  'fuzzy',
  'gastric',
  'gay',
  'general',
  'generous',
  'genetic',
  'gentle',
  'genuine',
  'geographical',
  'german',
  'giant',
  'gigantic',
  'given',
  'glad',
  'glamorous',
  'gleaming',
  'global',
  'glorious',
  'golden',
  'good',
  'gorgeous',
  'gothic',
  'governing',
  'graceful',
  'gradual',
  'grand',
  'grateful',
  'greasy',
  'great',
  'greek',
  'green',
  'grey',
  'grieving',
  'grim',
  'gross',
  'grotesque',
  'growing',
  'grubby',
  'grumpy',
  'guilty',
  'handicapped',
  'handsome',
  'happy',
  'hard',
  'harsh',
  'head',
  'healthy',
  'heavy',
  'helpful',
  'helpless',
  'hidden',
  'high',
  'high-pitched',
  'hilarious',
  'hissing',
  'historic',
  'historical',
  'hollow',
  'holy',
  'homeless',
  'homely',
  'hon',
  'honest',
  'horizontal',
  'horrible',
  'hostile',
  'hot',
  'huge',
  'human',
  'hungry',
  'hurt',
  'hushed',
  'husky',
  'icy',
  'ideal',
  'identical',
  'ideological',
  'ill',
  'illegal',
  'imaginative',
  'immediate',
  'immense',
  'imperial',
  'implicit',
  'important',
  'impossible',
  'impressed',
  'impressive',
  'improved',
  'inadequate',
  'inappropriate',
  'inc',
  'inclined',
  'increased',
  'increasing',
  'incredible',
  'independent',
  'indian',
  'indirect',
  'individual',
  'industrial',
  'inevitable',
  'influential',
  'informal',
  'inherent',
  'initial',
  'injured',
  'inland',
  'inner',
  'innocent',
  'innovative',
  'inquisitive',
  'instant',
  'institutional',
  'insufficient',
  'intact',
  'integral',
  'integrated',
  'intellectual',
  'intelligent',
  'intense',
  'intensive',
  'interested',
  'interesting',
  'interim',
  'interior',
  'intermediate',
  'internal',
  'international',
  'intimate',
  'invisible',
  'involved',
  'iraqi',
  'irish',
  'irrelevant',
  'islamic',
  'isolated',
  'israeli',
  'italian',
  'itchy',
  'japanese',
  'jealous',
  'jewish',
  'jittery',
  'joint',
  'jolly',
  'joyous',
  'judicial',
  'juicy',
  'junior',
  'just',
  'keen',
  'key',
  'kind',
  'known',
  'korean',
  'labour',
  'large',
  'large-scale',
  'late',
  'latin',
  'lazy',
  'leading',
  'left',
  'legal',
  'legislative',
  'legitimate',
  'lengthy',
  'lesser',
  'level',
  'lexical',
  'liable',
  'liberal',
  'light',
  'like',
  'likely',
  'limited',
  'linear',
  'linguistic',
  'liquid',
  'literary',
  'little',
  'live',
  'lively',
  'living',
  'local',
  'logical',
  'lonely',
  'long',
  'long-term',
  'loose',
  'lost',
  'loud',
  'lovely',
  'low',
  'loyal',
  'lucky',
  'mad',
  'magenta',
  'magic',
  'magnetic',
  'magnificent',
  'main',
  'major',
  'male',
  'mammoth',
  'managerial',
  'managing',
  'manual',
  'many',
  'marginal',
  'marine',
  'marked',
  'married',
  'marvellous',
  'marxist',
  'mass',
  'massive',
  'mathematical',
  'mature',
  'maximum',
  'mean',
  'meaningful',
  'mechanical',
  'medical',
  'medieval',
  'melodic',
  'melted',
  'mental',
  'mere',
  'metropolitan',
  'mid',
  'middle',
  'middle-class',
  'mighty',
  'mild',
  'military',
  'miniature',
  'minimal',
  'minimum',
  'ministerial',
  'minor',
  'miserable',
  'misleading',
  'missing',
  'misty',
  'mixed',
  'moaning',
  'mobile',
  'moderate',
  'modern',
  'modest',
  'molecular',
  'monetary',
  'monthly',
  'moral',
  'motionless',
  'muddy',
  'multiple',
  'mushy',
  'musical',
  'mute',
  'mutual',
  'mysterious',
  'naked',
  'narrow',
  'nasty',
  'national',
  'native',
  'natural',
  'naughty',
  'naval',
  'near',
  'nearby',
  'neat',
  'necessary',
  'negative',
  'neighbouring',
  'nervous',
  'net',
  'neutral',
  'new',
  'nice',
  'nineteenth-century',
  'noble',
  'noisy',
  'normal',
  'northern',
  'nosy',
  'notable',
  'novel',
  'nuclear',
  'numerous',
  'nursing',
  'nutritious',
  'nutty',
  'obedient',
  'objective',
  'obliged',
  'obnoxious',
  'obvious',
  'occasional',
  'occupational',
  'odd',
  'official',
  'ok',
  'okay',
  'old',
  'old-fashioned',
  'olympic',
  'only',
  'open',
  'operational',
  'opposite',
  'optimistic',
  'oral',
  'orange',
  'ordinary',
  'organic',
  'organisational',
  'original',
  'orthodox',
  'other',
  'outdoor',
  'outer',
  'outrageous',
  'outside',
  'outstanding',
  'overall',
  'overseas',
  'overwhelming',
  'painful',
  'pale',
  'palestinian',
  'panicky',
  'parallel',
  'parental',
  'parliamentary',
  'part-time',
  'partial',
  'particular',
  'passing',
  'passive',
  'past',
  'patient',
  'payable',
  'peaceful',
  'peculiar',
  'perfect',
  'permanent',
  'persistent',
  'personal',
  'petite',
  'philosophical',
  'physical',
  'pink',
  'plain',
  'planned',
  'plastic',
  'pleasant',
  'pleased',
  'poised',
  'polish',
  'polite',
  'political',
  'poor',
  'popular',
  'positive',
  'possible',
  'post-war',
  'potential',
  'powerful',
  'practical',
  'precious',
  'precise',
  'preferred',
  'pregnant',
  'preliminary',
  'premier',
  'prepared',
  'present',
  'presidential',
  'pretty',
  'previous',
  'prickly',
  'primary',
  'prime',
  'primitive',
  'principal',
  'printed',
  'prior',
  'private',
  'probable',
  'productive',
  'professional',
  'profitable',
  'profound',
  'progressive',
  'prominent',
  'promising',
  'proper',
  'proposed',
  'prospective',
  'protective',
  'protestant',
  'proud',
  'provincial',
  'psychiatric',
  'psychological',
  'public',
  'puny',
  'pure',
  'purple',
  'purring',
  'puzzled',
  'quaint',
  'qualified',
  'quick',
  'quickest',
  'quiet',
  'racial',
  'radical',
  'rainy',
  'random',
  'rapid',
  'rare',
  'raspy',
  'rational',
  'ratty',
  'raw',
  'ready',
  'real',
  'realistic',
  'rear',
  'reasonable',
  'recent',
  'red',
  'reduced',
  'redundant',
  'regional',
  'registered',
  'regular',
  'regulatory',
  'related',
  'relative',
  'relaxed',
  'relevant',
  'reliable',
  'relieved',
  'religious',
  'reluctant',
  'remaining',
  'remarkable',
  'remote',
  'renewed',
  'representative',
  'repulsive',
  'required',
  'resident',
  'residential',
  'resonant',
  'respectable',
  'respective',
  'responsible',
  'resulting',
  'retail',
  'retired',
  'revolutionary',
  'rich',
  'ridiculous',
  'right',
  'rigid',
  'ripe',
  'rising',
  'rival',
  'roasted',
  'robust',
  'rolling',
  'roman',
  'romantic',
  'rotten',
  'rough',
  'round',
  'royal',
  'rubber',
  'rude',
  'ruling',
  'running',
  'rural',
  'russian',
  'sacred',
  'sad',
  'safe',
  'salty',
  'satisfactory',
  'satisfied',
  'scared',
  'scary',
  'scattered',
  'scientific',
  'scornful',
  'scottish',
  'scrawny',
  'screeching',
  'secondary',
  'secret',
  'secure',
  'select',
  'selected',
  'selective',
  'selfish',
  'semantic',
  'senior',
  'sensible',
  'sensitive',
  'separate',
  'serious',
  'severe',
  'sexual',
  'shaggy',
  'shaky',
  'shallow',
  'shared',
  'sharp',
  'sheer',
  'shiny',
  'shivering',
  'shocked',
  'short',
  'short-term',
  'shrill',
  'shy',
  'sick',
  'significant',
  'silent',
  'silky',
  'silly',
  'similar',
  'simple',
  'single',
  'skilled',
  'skinny',
  'sleepy',
  'slight',
  'slim',
  'slimy',
  'slippery',
  'slow',
  'small',
  'smart',
  'smiling',
  'smoggy',
  'smooth',
  'so-called',
  'social',
  'socialist',
  'soft',
  'solar',
  'sole',
  'solid',
  'sophisticated',
  'sore',
  'sorry',
  'sound',
  'sour',
  'southern',
  'soviet',
  'spanish',
  'spare',
  'sparkling',
  'spatial',
  'special',
  'specific',
  'specified',
  'spectacular',
  'spicy',
  'spiritual',
  'splendid',
  'spontaneous',
  'sporting',
  'spotless',
  'spotty',
  'square',
  'squealing',
  'stable',
  'stale',
  'standard',
  'static',
  'statistical',
  'statutory',
  'steady',
  'steep',
  'sticky',
  'stiff',
  'still',
  'stingy',
  'stormy',
  'straight',
  'straightforward',
  'strange',
  'strategic',
  'strict',
  'striking',
  'striped',
  'strong',
  'structural',
  'stuck',
  'stupid',
  'subjective',
  'subsequent',
  'substantial',
  'subtle',
  'successful',
  'successive',
  'sudden',
  'sufficient',
  'suitable',
  'sunny',
  'super',
  'superb',
  'superior',
  'supporting',
  'supposed',
  'supreme',
  'sure',
  'surprised',
  'surprising',
  'surrounding',
  'surviving',
  'suspicious',
  'sweet',
  'swift',
  'swiss',
  'symbolic',
  'sympathetic',
  'systematic',
  'tall',
  'tame',
  'tan',
  'tart',
  'tasteless',
  'tasty',
  'technical',
  'technological',
  'teenage',
  'temporary',
  'tender',
  'tense',
  'terrible',
  'territorial',
  'testy',
  'then',
  'theoretical',
  'thick',
  'thin',
  'thirsty',
  'thorough',
  'thoughtful',
  'thoughtless',
  'thundering',
  'tight',
  'tiny',
  'tired',
  'top',
  'tory',
  'total',
  'tough',
  'toxic',
  'traditional',
  'tragic',
  'tremendous',
  'tricky',
  'tropical',
  'troubled',
  'turkish',
  'typical',
  'ugliest',
  'ugly',
  'ultimate',
  'unable',
  'unacceptable',
  'unaware',
  'uncertain',
  'unchanged',
  'uncomfortable',
  'unconscious',
  'underground',
  'underlying',
  'unemployed',
  'uneven',
  'unexpected',
  'unfair',
  'unfortunate',
  'unhappy',
  'uniform',
  'uninterested',
  'unique',
  'united',
  'universal',
  'unknown',
  'unlikely',
  'unnecessary',
  'unpleasant',
  'unsightly',
  'unusual',
  'unwilling',
  'upper',
  'upset',
  'uptight',
  'urban',
  'urgent',
  'used',
  'useful',
  'useless',
  'usual',
  'vague',
  'valid',
  'valuable',
  'variable',
  'varied',
  'various',
  'varying',
  'vast',
  'verbal',
  'vertical',
  'very',
  'victorian',
  'victorious',
  'video-taped',
  'violent',
  'visible',
  'visiting',
  'visual',
  'vital',
  'vivacious',
  'vivid',
  'vocational',
  'voiceless',
  'voluntary',
  'vulnerable',
  'wandering',
  'warm',
  'wasteful',
  'watery',
  'weak',
  'wealthy',
  'weary',
  'wee',
  'weekly',
  'weird',
  'welcome',
  'well',
  'well-known',
  'welsh',
  'western',
  'wet',
  'whispering',
  'white',
  'whole',
  'wicked',
  'wide',
  'wide-eyed',
  'widespread',
  'wild',
  'willing',
  'wise',
  'witty',
  'wonderful',
  'wooden',
  'working',
  'working-class',
  'worldwide',
  'worried',
  'worrying',
  'worthwhile',
  'worthy',
  'written',
  'wrong',
  'yellow',
  'young',
  'yummy',
  'zany',
  'zealous',
];
const plants = [
  {
    name: 'Alder',
    species: 'Alnus',
  },
  {
    name: 'Black alder',
    species: 'Alnus glutinosa, Ilex verticillata',
  },
  {
    name: 'Common alder',
    species: 'Alnus glutinosa',
  },
  {
    name: 'False alder',
    species: 'Ilex verticillata',
  },
  {
    name: 'Gray alder',
    species: 'Alnus incana',
  },
  {
    name: 'Speckled alder',
    species: 'Alnus incana',
  },
  {
    name: 'Striped alder',
    species: 'Ilex verticillata',
  },
  {
    name: 'White alder',
    species: 'Alnus incana, Ilex verticillata',
  },
  {
    name: 'Almond',
    species: 'Prunus amygdalus',
  },
  {
    name: 'Tall ambrosia',
    species: 'Ambrosia trifida',
  },
  {
    name: 'Amy root',
    species: 'Apocynum cannabinum',
  },
  {
    name: 'Apple',
    species: 'Malus domestica',
  },
  {
    name: 'Apricot',
    species: 'Prunus armeniaca',
  },
  {
    name: 'Arfaj',
    species: 'Rhanterium epapposum',
  },
  {
    name: 'Arizona sycamore',
    species: 'Platanus wrighitii',
  },
  {
    name: 'Arrowwood',
    species: 'Cornus florida',
  },
  {
    name: 'Indian arrowwood',
    species: 'Cornus florida',
  },
  {
    name: 'Ash',
    species: 'Fraxinus spp.',
  },
  {
    name: 'Black ash',
    species: 'Acer negundo, Fraxinus nigra',
  },
  {
    name: 'Blue ash',
    species: 'Fraxinus pennsylvanica',
  },
  {
    name: 'Cane ash',
    species: 'Fraxinus americana',
  },
  {
    name: 'Green ash',
    species: 'Fraxinus pennsylvanica',
  },
  {
    name: 'Maple ash',
    species: 'Acer negundo',
  },
  {
    name: 'Red ash',
    species: 'Fraxinus pennsylvanica',
  },
  {
    name: 'River ash',
    species: 'Fraxinus pennsylvanica',
  },
  {
    name: 'Swamp ash',
    species: 'Fraxinus pennsylvanica',
  },
  {
    name: 'White ash',
    species: 'Fraxinus americana',
  },
  {
    name: 'Water ash',
    species: 'Acer negundo, Fraxinus pennsylvanica',
  },
  {
    name: 'Azolla',
    species: 'Azolla',
  },
  {
    name: 'Carolina azolla',
    species: 'Azolla caroliniana',
  },
  {
    name: 'Bamboo',
    species: 'Bambuseae',
  },
  {
    name: 'Banana',
    species: 'mainly Musa × paradisica, but also other Musa species and hybrids',
  },
  {
    name: 'Baobab',
    species: 'Adansonia',
  },
  {
    name: 'Bay',
    species: 'Laurus spp. or Umbellularia spp.',
  },
  {
    name: 'Bay laurel',
    species: 'Laurus nobilis (culinary)',
  },
  {
    name: 'California bay',
    species: 'Umbellularia californica',
  },
  {
    name: 'Bean',
    species: 'Fabaceae, specifically Phaseolus spp.',
  },
  {
    name: 'Bearberry',
    species: 'Ilex decidua',
  },
  {
    name: 'Bear corn',
    species: 'Veratrum viride',
  },
  {
    name: 'Beech',
    species: 'Fagus',
  },
  {
    name: 'Blue bindweed',
    species: 'Solanum dulcamara',
  },
  {
    name: "Bird's nest",
    species: 'Daucus carota',
  },
  {
    name: "Bird's nest plant",
    species: 'Daucus carota',
  },
  {
    name: 'Birch',
    species: 'Betula spp.',
  },
  {
    name: 'Black birch',
    species: 'Betula lenta, Betula nigra',
  },
  {
    name: 'Bolean birch',
    species: 'Betula papyrifera',
  },
  {
    name: 'Canoe birch',
    species: 'Betula papyrifera',
  },
  {
    name: 'Cherry birch',
    species: 'Betula lenta',
  },
  {
    name: 'European weeping birch',
    species: 'Betula pendula',
  },
  {
    name: 'European white birch',
    species: 'Betula pendula',
  },
  {
    name: 'Gray birch',
    species: 'Betula alleghaniensis',
  },
  {
    name: 'Mahogany birch',
    species: 'Betula lenta',
  },
  {
    name: 'Paper birch',
    species: 'Betula papyrifera',
  },
  {
    name: 'Red birch',
    species: 'Betula nigra',
  },
  {
    name: 'River birch',
    species: 'Betula nigra, Betula lenta',
  },
  {
    name: 'Silver birch',
    species: 'Betula papyrifera',
  },
  {
    name: 'Spice birch',
    species: 'Betula lenta',
  },
  {
    name: 'Sweet birch',
    species: 'Betula lenta',
  },
  {
    name: 'Water birch',
    species: 'Betula nigra',
  },
  {
    name: 'Weeping birch',
    species: 'Betula pendula',
  },
  {
    name: 'White birch',
    species: 'Betula papyrifera, Betula pendula',
  },
  {
    name: 'Yellow birch',
    species: 'Betula alleghaniensis',
  },
  {
    name: 'Bittercress',
    species: 'Barbarea vulgaris, Cardamine bulbosa, Cardamine hirsuta',
  },
  {
    name: 'Hairy bittercress',
    species: 'Cardamine hirsuta',
  },
  {
    name: 'Bittersweet',
    species: 'Solanum dulcamara',
  },
  {
    name: 'Trailing bittersweet',
    species: 'Solanum dulcamara',
  },
  {
    name: 'Bitterweed',
    species:
      'Any plant in the Ambrosia genus, specially Ambrosia artemisiifolia, Artemisia trifida, Helenium amarum',
  },
  {
    name: 'Blackberry',
    species: 'Rubus spp., Rubus pensilvanicus, Rubus occidentalis',
  },
  {
    name: 'Hispid swamp blackberry',
    species: 'Rubus hispidus',
  },
  {
    name: 'Pennsylvania blackberry',
    species: 'Rubus pensilvanicus',
  },
  {
    name: 'Running swamp blackberry',
    species: 'Rubus hispidus',
  },
  {
    name: 'Black cap',
    species: 'Rubus occidentalis',
  },
  {
    name: 'Black-eyed Susan',
    species: 'Rudbeckia hirta, Rudbeckia fulgida',
  },
  {
    name: 'Blackhaw',
    species: 'Viburnum prunifolium',
  },
  {
    name: 'Blackiehead',
    species: 'Rudbeckia hirta',
  },
  {
    name: 'Black-weed',
    species: 'Ambrosia artemisiifolia',
  },
  {
    name: 'Blueberry',
    species: 'Vaccinium (Cyanococcus) spp.',
  },
  {
    name: 'Blue-of-the-heavens',
    species: 'Allium caeruleum',
  },
  {
    name: 'Bow-wood',
    species: 'Maclura pomifera',
  },
  {
    name: 'Box',
    species: 'Buxus',
  },
  {
    name: 'False box',
    species: 'Cornus florida',
  },
  {
    name: 'Boxelder',
    species: 'Acer negundo',
  },
  {
    name: 'Boxwood',
    species: 'Buxus, Cornus florida',
  },
  {
    name: 'False boxwood',
    species: 'Cornus florida',
  },
  {
    name: 'Sand brier',
    species: 'Solanum carolinense',
  },
  {
    name: 'Brittlebush',
    species: 'Encelia farinosa',
  },
  {
    name: 'Broadleaf',
    species: 'Plantago major',
  },
  {
    name: 'Brown Betty',
    species: 'Rudbeckia hirta',
  },
  {
    name: 'Brown-eyed Susan',
    species: 'Rudbeckia hirta, Rudbeckia triloba',
  },
  {
    name: 'Buckeye (California buckeye)',
    species: 'Aesculus californica',
  },
  {
    name: 'buckeye',
    species: 'Aesculus spp.',
  },
  {
    name: 'Buffalo weed',
    species: 'Ambrosia trifida',
  },
  {
    name: 'Butterfly flower',
    species: 'Asclepias syriaca',
  },
  {
    name: 'Butterfly weed',
    species: 'Asclepias tuberosa',
  },
  {
    name: 'Cabbage',
    species: 'Brassica oleracea',
  },
  {
    name: 'Clumpfoot cabbage',
    species: 'Symplocarpus foetidus',
  },
  {
    name: 'Meadow cabbage',
    species: 'Symplocarpus foetidus',
  },
  {
    name: 'Skunk cabbage',
    species: 'Symplocarpus foetidus, Lysichiton spp.',
  },
  {
    name: 'Swamp cabbage',
    species: 'Symplocarpus foetidus',
  },
  {
    name: 'California bay',
    species: 'Umbellularia californica',
  },
  {
    name: 'California buckeye',
    species: 'Aesculus californica',
  },
  {
    name: 'California sycamore',
    species: 'Platanus racemosa',
  },
  {
    name: 'California walnut',
    species: 'Juglans californica',
  },
  {
    name: 'Canada root',
    species: 'Asclepias tuberosa',
  },
  {
    name: 'Cancer jalap',
    species: 'Phytolacca americana',
  },
  {
    name: 'Carrot',
    species: 'Daucus carota',
  },
  {
    name: 'Wild carrot',
    species: 'Daucus carota',
  },
  {
    name: 'Carrot weed',
    species: 'Ambrosia artemisiifolia',
  },
  {
    name: 'Cart track plant',
    species: 'Plantago major',
  },
  {
    name: 'Catalina ironwood',
    species: 'Lyonothamnus floribundus ssp. floribundus',
  },
  {
    name: 'Cherry',
    species: 'Prunus spp.',
  },
  {
    name: 'Black cherry',
    species: 'Prunus serotina',
  },
  {
    name: 'Cabinet cherry',
    species: 'Prunus serotina',
  },
  {
    name: 'Rum cherry',
    species: 'Prunus serotina',
  },
  {
    name: 'Whiskey cherry',
    species: 'Prunus serotina',
  },
  {
    name: 'Wild cherry',
    species: 'Prunus avium, Prunus serotina',
  },
  {
    name: 'Wild black cherry',
    species: 'Prunus serotina',
  },
  {
    name: 'Chestnut',
    species: 'Castanea spp.',
  },
  {
    name: 'Chigger flower',
    species: 'Asclepias tuberosa',
  },
  {
    name: 'Chrysanthemum',
    species: 'Dendranthema grandiflora, Chrysanthemum morifolium',
  },
  {
    name: '(True) cinnamon',
    species: 'Cinnamomum verum',
  },
  {
    name: 'Clove',
    species: 'Syzygium aromaticum',
  },
  {
    name: 'Clover',
    species: 'Trifolium spp.',
  },
  {
    name: 'Coakum',
    species: 'Phytolacca americana',
  },
  {
    name: 'Coconut',
    species: 'Cocos nucifera',
  },
  {
    name: 'Coffee plant',
    species: 'Coffea spp.',
  },
  {
    name: 'Colic weed',
    species: 'Corydalis flavula',
  },
  {
    name: 'Collard',
    species: 'Symplocarpus foetidus',
  },
  {
    name: "Hare's colwort",
    species: 'Sonchus oleraceus',
  },
  {
    name: 'Brilliant coneflower',
    species: 'Rudbeckia fulgida',
  },
  {
    name: 'Cutleaf coneflower',
    species: 'Rudbeckia laciniata',
  },
  {
    name: 'Eastern coneflower',
    species: 'Rudbeckia fulgida',
  },
  {
    name: 'Green-headed Coneflower',
    species: 'Rudbeckia laciniata',
  },
  {
    name: 'Orange coneflower',
    species: 'Rudbeckia fulgida',
  },
  {
    name: 'Tall coneflower',
    species: 'Rudbeckia laciniata',
  },
  {
    name: 'Thin-leaved Coneflower',
    species: 'Rudbeckia triloba',
  },
  {
    name: 'Three-leaved Coneflower',
    species: 'Rudbeckia triloba',
  },
  {
    name: 'Blueberry cornel',
    species: 'Cornus amomum',
  },
  {
    name: 'Silky cornel',
    species: 'Cornus amomum',
  },
  {
    name: 'White cornel',
    species: 'Cornus florida',
  },
  {
    name: 'Cornelian tree',
    species: 'Cornus florida',
  },
  {
    name: 'Corydalis',
    species: 'Corydalis spp.',
  },
  {
    name: 'Fern-leaf Corydalis',
    species: 'Corydalis chelidoniifolia',
  },
  {
    name: 'Golden corydalis',
    species: 'Corydalis aurea',
  },
  {
    name: 'Pale corydalis',
    species: 'Corydalis flavula, Corydalis sempervirens',
  },
  {
    name: 'Pink corydalis',
    species: 'Corydalis sempervirens',
  },
  {
    name: 'Yellow corydalis',
    species: 'Corydalis lutea, Corydalis flavula',
  },
  {
    name: 'Cotton plant',
    species: 'Gossypium',
  },
  {
    name: 'Creeping yellowcress',
    species: 'Rorippa sylvestris',
  },
  {
    name: 'Cress',
    species: '(several genera)',
  },
  {
    name: 'American cress',
    species: 'Barbarea verna',
  },
  {
    name: 'Bank cress',
    species: 'Barbarea verna',
  },
  {
    name: 'Belle Isle cress',
    species: 'Barbarea verna',
  },
  {
    name: 'Bermuda cress',
    species: 'Barbarea verna',
  },
  {
    name: 'Bulbous cress',
    species: 'Cardamine bulbosa',
  },
  {
    name: "Lamb's cress",
    species: 'Cardamine hirsuta',
  },
  {
    name: 'Land cress',
    species: 'Barbarea verna, Cardamine hirsuta',
  },
  {
    name: 'Scurvy cress',
    species: 'Barbarea verna',
  },
  {
    name: 'Spring cress',
    species: 'Cardamine bulbosa',
  },
  {
    name: 'Upland cress',
    species: 'Barbarea verna',
  },
  {
    name: 'Crowfoot',
    species: 'Cardamine concatenata',
  },
  {
    name: "Crow's nest",
    species: 'Daucus carota',
  },
  {
    name: "Crow's toes",
    species: 'Cardamine concatenata',
  },
  {
    name: 'Cucumber',
    species: 'Cucumis sativus',
  },
  {
    name: 'Brown daisy',
    species: 'Rudbeckia hirta',
  },
  {
    name: 'Common daisy, daisy',
    species: 'Bellis perennis',
  },
  {
    name: 'Gloriosa daisy',
    species: 'Rudbeckia hirta',
  },
  {
    name: 'Poorland daisy',
    species: 'Rudbeckia hirta',
  },
  {
    name: 'Yellow daisy',
    species: 'Rudbeckia hirta',
  },
  {
    name: 'Yellow ox-eye daisy',
    species: 'Rudbeckia hirta',
  },
  {
    name: 'Deadnettle',
    species: 'Lamium spp.',
  },
  {
    name: 'Henbit deadnettle',
    species: 'Lamium amplexicaule',
  },
  {
    name: 'Spotted deadnettle',
    species: 'Lamium maculatum',
  },
  {
    name: "Devil's bite",
    species: 'Veratrum viride',
  },
  {
    name: "Devil's darning needle",
    species: 'Clematis virginiana',
  },
  {
    name: "Devil's nose",
    species: 'Clematis virginiana',
  },
  {
    name: "Devil's plague",
    species: 'Daucus carota',
  },
  {
    name: 'Bristly dewberry',
    species: 'Rubus hispidus',
  },
  {
    name: 'Swamp dewberry',
    species: 'Rubus hispidus',
  },
  {
    name: 'Dindle',
    species: 'Sonchus arvensis',
  },
  {
    name: 'Dogwood',
    species: 'Cornus spp.',
  },
  {
    name: 'American dogwood',
    species: 'Cornus florida',
  },
  {
    name: 'Florida dogwood',
    species: 'Cornus florida',
  },
  {
    name: 'Flowering dogwood',
    species: 'Cornus florida',
  },
  {
    name: 'Japanese flowering dogwood',
    species: 'Cornus kousa',
  },
  {
    name: 'Kousa dogwood',
    species: 'Cornus kousa',
  },
  {
    name: 'Drumstick',
    species: 'Moringa oleifera',
  },
  {
    name: 'Pacific dogwood',
    species: 'Cornus nuttallii',
  },
  {
    name: 'Silky dogwood',
    species: 'Cornus amomum',
  },
  {
    name: 'Swamp dogwood',
    species: 'Cornus amomum',
  },
  {
    name: 'Duck retten',
    species: 'Veratrum viride',
  },
  {
    name: 'Duscle',
    species: 'Solanum nigrum',
  },
  {
    name: 'Dye-leaves',
    species: 'Ilex glabra',
  },
  {
    name: 'Earth gall',
    species: 'Veratrum viride',
  },
  {
    name: "English bull's eye",
    species: 'Rudbeckia hirta',
  },
  {
    name: 'Eucalyptus',
    species: 'Eucalyptus spp.',
  },
  {
    name: 'Extinguisher moss',
    species: 'Encalypta',
  },
  {
    name: 'Eytelia',
    species: 'Amphipappus',
  },
  {
    name: 'Fair-maid-of-France',
    species: 'Achillea ptarmica',
  },
  {
    name: 'Fellenwort',
    species: 'Solanum dulcamara',
  },
  {
    name: 'Felonwood',
    species: 'Solanum dulcamara',
  },
  {
    name: 'Felonwort',
    species: 'Solanum dulcamara',
  },
  {
    name: 'Fennel',
    species: 'Foeniculum vulgare',
  },
  {
    name: 'Boston fern or sword fern',
    species: 'Nephrolepis exaltata',
  },
  {
    name: 'Christmas fern',
    species: 'Polystichum acrostichoides',
  },
  {
    name: 'Coast polypody',
    species: 'Polypodium scouleri',
  },
  {
    name: 'Kimberly queen fern',
    species: 'Nephrolepis obliterata',
  },
  {
    name: 'Korean rock fern',
    species: 'Polystichum tsus-simense',
  },
  {
    name: 'Mosquito fern',
    species: 'Azolla caroliniana',
  },
  {
    name: 'Sword ferns',
    species: 'Polystichum spp.',
  },
  {
    name: 'Water fern',
    species: 'Azolla caroliniana',
  },
  {
    name: 'Western sword fern',
    species: 'Polystichum munitum',
  },
  {
    name: 'Feverbush',
    species: 'Ilex verticillata',
  },
  {
    name: 'Feverfew',
    species: 'Tanacetum parthenium',
  },
  {
    name: 'Fig',
    species: 'Ficus spp.',
  },
  {
    name: 'Common fig',
    species: 'Ficus carica',
  },
  {
    name: 'European flax',
    species: 'Linum usitatissimum',
  },
  {
    name: 'New Zealand flax',
    species: 'Phormium tenax, Phormium colensoi',
  },
  {
    name: 'Fluxroot',
    species: 'Asclepias tuberosa',
  },
  {
    name: 'Yellow fumewort',
    species: 'Corydalis flavula',
  },
  {
    name: 'Gallberry',
    species: 'Ilex glabra',
  },
  {
    name: 'Garget',
    species: 'Phytolacca americana',
  },
  {
    name: 'Golden garlic',
    species: 'Allium moly',
  },
  {
    name: 'Wild garlic',
    species: 'Allium canadense',
  },
  {
    name: 'Garlic mustard',
    species: 'Alliaria petiolata',
  },
  {
    name: 'Garlic root',
    species: 'Alliaria petiolata',
  },
  {
    name: "Dame's gilliflower",
    species: 'Hesperis matronalis',
  },
  {
    name: 'Night scented gilliflower',
    species: 'Hesperis matronalis',
  },
  {
    name: "Queen's gilliflower",
    species: 'Hesperis matronalis',
  },
  {
    name: "Rogue's gilliflower",
    species: 'Hesperis matronalis',
  },
  {
    name: 'Winter gilliflower',
    species: 'Hesperis matronalis',
  },
  {
    name: 'Golden buttons',
    species: 'Tanacetum vulgare',
  },
  {
    name: 'Goldenglow',
    species: 'Rudbeckia laciniata',
  },
  {
    name: 'Golden Jerusalem',
    species: 'Rudbeckia hirta',
  },
  {
    name: 'Gordaldo',
    species: 'Achillea millefolium',
  },
  {
    name: 'Goose tongue',
    species: 'Achillea ptarmica',
  },
  {
    name: 'Grapefruit',
    species: 'Citrus × paradisi',
  },
  {
    name: 'Grapevine',
    species: 'Vitis',
  },
  {
    name: 'Groundberry',
    species: 'Rubus hispidus',
  },
  {
    name: 'Bristly groundberry',
    species: 'Rubus hispidus',
  },
  {
    name: 'Gutweed',
    species: 'Sonchus arvensis',
  },
  {
    name: 'Haldi',
    species: 'Curcuma domestica',
  },
  {
    name: 'Rock harlequin',
    species: 'Corydalis sempervirens',
  },
  {
    name: 'Yellow harlequin',
    species: 'Corydalis flavula',
  },
  {
    name: 'Hay fever weed',
    species: 'Ambrosia artemisiifolia, Artemisia trifida',
  },
  {
    name: 'Healing blade',
    species: 'Plantago major',
  },
  {
    name: 'Hedge plant',
    species: 'Maclura pomifera',
  },
  {
    name: 'Hellebore',
    species: 'Helleborus',
  },
  {
    name: 'American white hellebore',
    species: 'Veratrum viride',
  },
  {
    name: 'Big hellebore',
    species: 'Veratrum viride',
  },
  {
    name: 'Black hellebore',
    species: 'Veratrum nigrum',
  },
  {
    name: 'European white hellebore',
    species: 'Veratrum album',
  },
  {
    name: 'False hellebore',
    species: 'Veratrum album, Veratrum viride',
  },
  {
    name: 'Swamp hellebore',
    species: 'Veratrum viride',
  },
  {
    name: 'White hellebore',
    species: 'Veratrum album, Veratrum viride',
  },
  {
    name: 'Hemp',
    species: 'Cannabis spp., specifically Cannabis sativa',
  },
  {
    name: 'Hemp dogbane',
    species: 'Apocynum cannabinum',
  },
  {
    name: 'Hen plant',
    species: 'Plantago major',
  },
  {
    name: 'Herb barbara',
    species: 'Barbarea vulgaris',
  },
  {
    name: 'Hogweed',
    species: 'Ambrosia artemisiifolia',
  },
  {
    name: 'Holly',
    species: 'Ilex spp.',
  },
  {
    name: 'Deciduous holly',
    species: 'Ilex decidua, Ilex verticillata',
  },
  {
    name: 'European holly',
    species: 'Ilex aquifolium',
  },
  {
    name: 'Inkberry holly',
    species: 'Ilex glabra',
  },
  {
    name: 'Meadow holly',
    species: 'Ilex decidua',
  },
  {
    name: 'Swamp holly',
    species: 'Ilex decidua',
  },
  {
    name: 'Winterberry holly',
    species: 'Ilex verticillata',
  },
  {
    name: 'Horse cane',
    species: 'Ambrosia trifida',
  },
  {
    name: "Hound's berry",
    species: 'Solanum nigrum',
  },
  {
    name: 'Huckleberry',
    species: 'Vaccinium spp.',
  },
  {
    name: 'Evergreen huckleberry',
    species: 'Vaccinium ovatum',
  },
  {
    name: 'Trailing red huckleberry',
    species: 'Vaccinium parvifolium',
  },
  {
    name: 'Houseleek',
    species: 'Sempervivum tectorum',
  },
  {
    name: 'Indian hemp',
    species: 'various genera',
  },
  {
    name: 'Indian hemp',
    species: 'Apocynum cannabinum, Cannabis indica',
  },
  {
    name: 'White Indian hemp',
    species: 'Asclepias incarnata',
  },
  {
    name: 'Indian paintbrush',
    species: 'Castilleja, Castilleja mutis, Asclepias tuberosa',
  },
  {
    name: 'Indian posy',
    species: 'Asclepias tuberosa',
  },
  {
    name: 'Inkberry',
    species: 'Ilex glabra, Phytolacca americana',
  },
  {
    name: 'Isle of Man cabbage',
    species: 'Coincya monensis',
  },
  {
    name: 'Itchweed',
    species: 'Veratrum viride',
  },
  {
    name: 'Ivy',
    species: 'Hedera spp.',
  },
  {
    name: 'Jack-by-the-hedge',
    species: 'Alliaria petiolata',
  },
  {
    name: 'Jack-in-the-bush',
    species: 'Alliaria petiolata',
  },
  {
    name: 'Juneberry',
    species: 'Amelanchier canadensis',
  },
  {
    name: 'Juniper',
    species: 'Various species in the genus Juniperus',
  },
  {
    name: 'Keek',
    species: 'Rorippa sylvestris',
  },
  {
    name: 'Kinnikinnik',
    species: 'Cornus amomum',
  },
  {
    name: 'Kousa',
    species: 'Cornus kousa',
  },
  {
    name: 'Kudzu',
    species: 'Pueraria lobata',
  },
  {
    name: 'Laceflower',
    species: 'Daucus carota',
  },
  {
    name: "Lamb's foot",
    species: 'Plantago major',
  },
  {
    name: 'Lavender',
    species: 'Lavandula',
  },
  {
    name: 'Leek',
    species: 'Allium',
  },
  {
    name: 'Lemon',
    species: 'Citrus × limon',
  },
  {
    name: 'Lettuce',
    species: 'Lactuca sativa',
  },
  {
    name: 'Lily leek',
    species: 'Allium moly',
  },
  {
    name: 'Summer lilac',
    species: 'Hesperis matronalis',
  },
  {
    name: 'Love vine',
    species: 'Clematis virginiana',
  },
  {
    name: 'Maize',
    species: 'Zea mays',
  },
  {
    name: 'Mango',
    species: 'Mangifera indica',
  },
  {
    name: 'Maple',
    species: 'Acer',
  },
  {
    name: 'Ash-leaved maple',
    species: 'Acer negundo',
  },
  {
    name: 'Black maple',
    species: 'Acer nigrum',
  },
  {
    name: 'Creek maple',
    species: 'Acer saccharinum',
  },
  {
    name: 'Cutleaf maple',
    species: 'Acer negundo',
  },
  {
    name: 'Maple ash',
    species: 'Acer negundo',
  },
  {
    name: 'Moose maple',
    species: 'Acer pensylvanicum',
  },
  {
    name: 'Red river maple',
    species: 'Acer negundo',
  },
  {
    name: 'River maple',
    species: 'Acer saccharinum',
  },
  {
    name: 'Silver maple',
    species: 'Acer saccharinum',
  },
  {
    name: 'Silverleaf maple',
    species: 'Acer saccharinum',
  },
  {
    name: 'Soft maple',
    species: 'Acer saccharinum',
  },
  {
    name: 'Striped maple',
    species: 'Acer pensylvanicum',
  },
  {
    name: 'Sugar maple',
    species: 'Acer saccharum (main use), Acer barbatum, Acer leucoderme,',
  },
  {
    name: 'Swamp maple',
    species: 'Acer saccharinum',
  },
  {
    name: 'Water maple',
    species: 'Acer saccharinum',
  },
  {
    name: 'White maple',
    species: 'Acer saccharinum',
  },
  {
    name: 'Mesquite',
    species: 'Prosopis',
  },
  {
    name: 'Honey mesquite',
    species: 'Prosopis glandulosa',
  },
  {
    name: 'Screwbean mesquite',
    species: 'Prosopis pubescens',
  },
  {
    name: 'Milfoil',
    species: 'Achillea millefolium',
  },
  {
    name: 'Milkweed',
    species: 'Asclepias, Sonchus oleraceus',
  },
  {
    name: 'Blunt-leaved Milkweed',
    species: 'Asclepias amplexicaulis',
  },
  {
    name: 'Common milkweed',
    species: 'Asclepias syriaca',
  },
  {
    name: 'Horsetail milkweed',
    species: 'Asclepias verticillata',
  },
  {
    name: 'Orange milkweed',
    species: 'Asclepias tuberosa',
  },
  {
    name: 'Swamp milkweed',
    species: 'Asclepias incarnata',
  },
  {
    name: 'Rose milkweed',
    species: 'Asclepias incarnata',
  },
  {
    name: 'Whorled milkweed',
    species: 'Asclepias verticillata',
  },
  {
    name: 'Yellow milkweed',
    species: 'Asclepias tuberosa',
  },
  {
    name: 'Milky tassel',
    species: 'Sonchus oleraceus',
  },
  {
    name: 'Moosewood',
    species: 'Acer pensylvanicum',
  },
  {
    name: 'Petty morel',
    species: 'Solanum nigrum',
  },
  {
    name: 'Mosquito plant',
    species: 'Azolla caroliniana',
  },
  {
    name: 'Mother-of-the-evening',
    species: 'Hesperis matronalis',
  },
  {
    name: 'Mountain mahogany',
    species: 'Betula lenta',
  },
  {
    name: 'Mulberry',
    species: 'Morus',
  },
  {
    name: 'Red mulberry',
    species: 'Morus rubra',
  },
  {
    name: 'White mulberry',
    species: 'Morus alba',
  },
  {
    name: 'Flowering Dogwood',
    species: 'Cornus florida',
  },
  {
    name: 'Neem',
    species: 'Azadirachta indica',
  },
  {
    name: 'Bull nettle',
    species: 'Solanum carolinense',
  },
  {
    name: 'Carolina horse nettle',
    species: 'Solanum carolinense',
  },
  {
    name: 'Horse nettle',
    species: 'Solanum carolinense',
  },
  {
    name: 'American nightshade',
    species: 'Phytolacca americana, Solanum americanum',
  },
  {
    name: 'Bitter nightshade',
    species: 'Solanum dulcamara',
  },
  {
    name: 'Black nightshade',
    species: 'Solanum nigrum, Solanum americanum',
  },
  {
    name: 'Climbing nightshade',
    species: 'Solanum dulcamara',
  },
  {
    name: 'Deadly nightshade',
    species: 'Solanum nigrum',
  },
  {
    name: 'Garden nightshade',
    species: 'Solanum nigrum',
  },
  {
    name: 'Trailing nightshade',
    species: 'Solanum dulcamara',
  },
  {
    name: 'Trailing violet nightshade',
    species: 'Solanum dulcamara',
  },
  {
    name: 'Woody nightshade',
    species: 'Solanum dulcamara',
  },
  {
    name: 'Nosebleed',
    species: 'Achillea millefolium',
  },
  {
    name: 'Blue oak',
    species: 'Quercus douglasii',
  },
  {
    name: 'Bur oak',
    species: 'Quercus macrocarpa',
  },
  {
    name: 'Champion oak',
    species: 'Quercus rubra',
  },
  {
    name: 'Coast live oak',
    species: 'Quercus agrifolia',
  },
  {
    name: 'Cork oak',
    species: 'Quercus suber',
  },
  {
    name: "Dyer's oak",
    species: 'Quercus velutina',
  },
  {
    name: 'Eastern black oak',
    species: "Quercus velutina'",
  },
  {
    name: 'English oak',
    species: 'Quercus robur',
  },
  {
    name: 'Island oak',
    species: 'Quercus. tomentella',
  },
  {
    name: "Mirbeck's oak",
    species: 'Quercus canariensis',
  },
  {
    name: 'Mossycup white oak',
    species: 'Quercus macrocarpa',
  },
  {
    name: 'Northern red oak',
    species: 'Quercus rubra',
  },
  {
    name: 'Pedunculate oak',
    species: 'Quercus robur',
  },
  {
    name: 'Pin oak',
    species: 'Quercus palustris',
  },
  {
    name: 'Red oak',
    species: 'Quercus rubra, Quercus coccinea',
  },
  {
    name: 'Scarlet oak',
    species: 'Quercus coccinea',
  },
  {
    name: 'Scrub oak',
    species: 'Quercus macrocarpa',
  },
  {
    name: 'Sessile oak',
    species: 'Quercus petraea',
  },
  {
    name: 'Spanish oak',
    species: 'Quercus coccinea, Quercus rubra',
  },
  {
    name: 'Spotted oak',
    species: 'Quercus velutina',
  },
  {
    name: 'Swamp oak',
    species: 'Quercus palustris, Quercus bicolor',
  },
  {
    name: 'Swamp Spanish oak',
    species: 'Quercus palustris',
  },
  {
    name: 'Swamp white oak',
    species: 'Quercus bicolor',
  },
  {
    name: 'Valley oak',
    species: 'Quercus lobata',
  },
  {
    name: 'White oak',
    species: 'Quercus alba',
  },
  {
    name: 'Yellowbark oak',
    species: 'Quercus velutina',
  },
  {
    name: 'Olive',
    species: 'Olea europaea',
  },
  {
    name: 'Onion',
    species: 'Allium',
  },
  {
    name: 'Common onion',
    species: 'Allium cepa',
  },
  {
    name: 'Giant onion',
    species: 'Allium giganteum',
  },
  {
    name: 'Nodding onion',
    species: 'Allium cernuum',
  },
  {
    name: 'Tree onion',
    species: 'Allium canadense',
  },
  {
    name: 'Wild onion',
    species: 'Allium canadense',
  },
  {
    name: 'Osage orange',
    species: 'Maclura pomifera',
  },
  {
    name: 'sweet orange',
    species: 'Citrus × sinensis',
  },
  {
    name: 'Wild orange',
    species: 'Maclura pomifera',
  },
  {
    name: 'Orange-root',
    species: 'Asclepias tuberosa',
  },
  {
    name: 'Osage',
    species: 'Maclura pomifera',
  },
  {
    name: 'Red osier',
    species: 'Cornus amomum',
  },
  {
    name: 'Parsley',
    species: 'Petroselinum crispum',
  },
  {
    name: 'Parsnip',
    species: 'Pastinaca sativa, Daucus carota',
  },
  {
    name: 'Pea',
    species: 'Pisum sativum',
  },
  {
    name: 'Peach',
    species: 'Prunus persica',
  },
  {
    name: 'Peanut',
    species: 'Arachis hypogaea',
  },
  {
    name: 'Pear',
    species: 'Pyrus',
  },
  {
    name: 'Bastard pellitory',
    species: 'Achillea ptarmica',
  },
  {
    name: 'European pellitory',
    species: 'Achillea ptarmica',
  },
  {
    name: 'Wild pellitory',
    species: 'Achillea ptarmica',
  },
  {
    name: 'Penny hedge',
    species: 'Alliaria petiolata',
  },
  {
    name: 'Pepper root',
    species: 'Cardamine concatenata',
  },
  {
    name: 'Pigeon berry',
    species: 'Phytolacca americana',
  },
  {
    name: 'Pine',
    species: 'Pinus',
  },
  {
    name: 'Pineapple',
    species: 'Ananas comosus',
  },
  {
    name: 'Pistachio',
    species: 'Pistacia vera',
  },
  {
    name: 'Plane (European sycamore)',
    species: 'Platanus acerifolia',
  },
  {
    name: 'Broadleaf plantain',
    species: 'Plantago major',
  },
  {
    name: 'Common plantain',
    species: 'Plantago major',
  },
  {
    name: 'Dooryard plantain',
    species: 'Plantago major',
  },
  {
    name: 'Greater plantain',
    species: 'Plantago major',
  },
  {
    name: 'Roundleaf plantain',
    species: 'Plantago major',
  },
  {
    name: 'Wayside plantain',
    species: 'Plantago major',
  },
  {
    name: 'Pleurisy root',
    species: 'Asclepias tuberosa',
  },
  {
    name: 'Pocan bush',
    species: 'Phytolacca americana',
  },
  {
    name: 'Poison ivy',
    species: 'Toxicodendron radicans',
  },
  {
    name: 'Poisonberry',
    species: 'Solanum dulcamara',
  },
  {
    name: 'Poisonflower',
    species: 'Solanum dulcamara',
  },
  {
    name: 'Poke',
    species: 'Phytolacca americana',
  },
  {
    name: 'Indian poke',
    species: 'Veratrum viride',
  },
  {
    name: 'Pokeroot',
    species: 'Phytolacca americana',
  },
  {
    name: 'Pokeweed',
    species: 'Phytolacca americana',
  },
  {
    name: 'Polkweed',
    species: 'Symplocarpus foetidus',
  },
  {
    name: 'Polecat weed',
    species: 'Symplocarpus foetidus',
  },
  {
    name: 'Poor Annie',
    species: 'Veratrum viride',
  },
  {
    name: "Poor man's mustard",
    species: 'Alliaria petiolata',
  },
  {
    name: 'Poplar',
    species: 'Populus',
  },
  {
    name: 'Poppy',
    species: 'Papaveraceae',
  },
  {
    name: 'Possumhaw',
    species: 'Ilex decidua',
  },
  {
    name: 'Potato',
    species: 'Solanum tuberosum',
  },
  {
    name: 'Pudina',
    species: 'Mentha indica',
  },
  {
    name: "Queen Anne's lace",
    species: 'Daucus carota, Anthriscus sylvestris',
  },
  {
    name: 'Quercitron',
    species: 'Quercus velutina',
  },
  {
    name: 'Radical weed',
    species: 'Solanum carolinense',
  },
  {
    name: 'Ragweed',
    species: 'Ambrosia',
  },
  {
    name: 'Common ragweed',
    species: 'Ambrosia artemisiifolia',
  },
  {
    name: 'Giant ragweed',
    species: 'Ambrosia trifida',
  },
  {
    name: 'Great ragweed',
    species: 'Ambrosia trifida',
  },
  {
    name: 'Ragwort',
    species: 'Senecio',
  },
  {
    name: 'Common ragwort',
    species: 'Senecio jacobaea',
  },
  {
    name: 'Hoary ragwort',
    species: 'Senecio erucifolius',
  },
  {
    name: 'Marsh ragwort',
    species: 'Senecio aquaticus',
  },
  {
    name: 'Oxford ragwort',
    species: 'Senecio squalidus',
  },
  {
    name: 'Silver ragwort',
    species: 'Senecio cineraria',
  },
  {
    name: 'Rantipole',
    species: 'Daucus carota',
  },
  {
    name: 'Rapeseed',
    species: 'Brassica napus',
  },
  {
    name: 'Raspberry',
    species: 'Rubus (Idaeobatus) spp.',
  },
  {
    name: 'Black raspberry',
    species: 'Rubus occidentalis',
  },
  {
    name: 'Purple raspberry',
    species: 'Rubus occidentalis',
  },
  {
    name: 'Redbrush',
    species: 'Cornus amomum',
  },
  {
    name: 'Redbud',
    species: 'Cercis spp.',
  },
  {
    name: 'Eastern redbud',
    species: 'Cercis canadensis',
  },
  {
    name: 'Western redbud',
    species: 'Cercis occidentalis',
  },
  {
    name: 'Judas-tree',
    species: 'Cercis siliquastrum',
  },
  {
    name: 'Red ink plant',
    species: 'Phytolacca americana',
  },
  {
    name: 'Redweed',
    species: 'Phytolacca americana',
  },
  {
    name: 'Rheumatism root',
    species: 'Apocynum cannabinum',
  },
  {
    name: 'Rhubarb',
    species: 'Rheum rhabarbarum',
  },
  {
    name: 'Ribwort',
    species: 'Plantago major',
  },
  {
    name: 'Asian rice',
    species: 'Oryza sativa',
  },
  {
    name: 'African rice',
    species: 'Oryza glaberrima',
  },
  {
    name: 'Roadweed',
    species: 'Plantago major',
  },
  {
    name: 'Rocket',
    species: '(several genera)',
  },
  {
    name: "Dame's rocket",
    species: 'Hesperis matronalis',
  },
  {
    name: 'Sweet rocket',
    species: 'Hesperis matronalis',
  },
  {
    name: 'Winter rocket',
    species: 'Barbarea vulgaris',
  },
  {
    name: 'Yellow rocket',
    species: 'Barbarea vulgaris',
  },
  {
    name: 'Rocketcress',
    species: 'Barbarea vulgaris',
  },
  {
    name: 'Rose',
    species: 'Rosa',
  },
  {
    name: 'Baby rose',
    species: 'Rosa multiflora',
  },
  {
    name: 'Dwarf wild rose',
    species: 'Rosa virginiana',
  },
  {
    name: 'Low rose',
    species: 'Rosa virginiana',
  },
  {
    name: 'Multiflora rose',
    species: 'Rosa multiflora',
  },
  {
    name: 'Prairie rose',
    species: 'Rosa virginiana',
  },
  {
    name: 'Rambler rose',
    species: 'Rosa multiflora',
  },
  {
    name: 'Wild rose',
    species: 'Rosa virginiana',
  },
  {
    name: 'Rosemary',
    species: 'Rosmarinus officinalis',
  },
  {
    name: 'Rye',
    species: 'Secale cereale',
  },
  {
    name: 'Saffron crocus',
    species: 'Crocus sativus',
  },
  {
    name: 'Sanguinary',
    species: 'Achillea millefolium',
  },
  {
    name: 'Sauce-alone',
    species: 'Alliaria petiolata',
  },
  {
    name: 'Scarlet berry',
    species: 'Solanum dulcamara',
  },
  {
    name: 'Scoke',
    species: 'Phytolacca americana',
  },
  {
    name: 'Scotch cap',
    species: 'Rubus occidentalis',
  },
  {
    name: 'Scrambled eggs',
    species: 'Corydalis aurea',
  },
  {
    name: 'Scurvy grass',
    species: 'Barbarea verna',
  },
  {
    name: 'Serviceberry',
    species: 'Amelanchier',
  },
  {
    name: 'Common serviceberry',
    species: 'Amelanchier arborea',
  },
  {
    name: 'Downy serviceberry',
    species: 'Amelanchier arborea',
  },
  {
    name: 'Shadblow serviceberry',
    species: 'Amelanchier canadensis',
  },
  {
    name: 'Shadblow',
    species: 'Amelanchier canadensis',
  },
  {
    name: 'Shadbush',
    species: 'Amelanchier canadensis',
  },
  {
    name: 'Silkweed',
    species: 'Asclepias syriaca',
  },
  {
    name: 'Swamp silkweed',
    species: 'Asclepias incarnata',
  },
  {
    name: 'Virginia silkweed',
    species: 'Asclepias syriaca',
  },
  {
    name: 'Skunkweed',
    species: 'Symplocarpus foetidus',
  },
  {
    name: 'Snakeberry',
    species: 'Solanum dulcamara',
  },
  {
    name: 'Snowdrop',
    species: 'Galanthus',
  },
  {
    name: 'Sorrel',
    species: 'Oxalis',
  },
  {
    name: 'Redwood sorrel',
    species: 'Oxalis oregana',
  },
  {
    name: 'Corn speedwell',
    species: 'Veronica arvensis',
  },
  {
    name: 'Wall speedwell',
    species: 'Veronica arvensis',
  },
  {
    name: 'Spoolwood',
    species: 'Betula papyrifera',
  },
  {
    name: 'Squaw bush',
    species: 'Cornus amomum',
  },
  {
    name: 'Stammerwort',
    species: 'Ambrosia artemisiifolia',
  },
  {
    name: 'Star-of-Persia',
    species: 'Allium cristophii',
  },
  {
    name: 'Stickweed',
    species: 'Ambrosia artemisiifolia',
  },
  {
    name: 'Strawberry',
    species: 'Fragaria × ananassa',
  },
  {
    name: 'Strawberry tree',
    species: 'Arbutus unedo',
  },
  {
    name: "Strawberry tree 'Marina'",
    species: 'Madrone',
  },
  {
    name: 'Sugarcane',
    species: 'Saccharum',
  },
  {
    name: 'Orange swallow-wort',
    species: 'Asclepias tuberosa',
  },
  {
    name: 'Silky swallow-wort',
    species: 'Asclepias syriaca',
  },
  {
    name: 'Sneezeweed',
    species: 'Achillea ptarmica',
  },
  {
    name: 'Sneezewort',
    species: 'Achillea ptarmica',
  },
  {
    name: 'Sunflower',
    species: 'Helianthus annuus',
  },
  {
    name: 'Sugarplum',
    species: 'Amelanchier canadensis',
  },
  {
    name: "Soldier's woundwort",
    species: 'Achillea millefolium',
  },
  {
    name: 'Stag bush',
    species: 'Viburnum prunifolium',
  },
  {
    name: 'Orange swallow-wort',
    species: 'Asclepias tuberosa',
  },
  {
    name: 'Silky swallow-wort',
    species: 'Asclepias syriaca',
  },
  {
    name: 'Sweet potato',
    species: 'Ipomoea batatas',
  },
  {
    name: 'Sweet potato vine',
    species: 'Ipomoea batatas',
  },
  {
    name: 'Swinies',
    species: 'Sonchus oleraceus',
  },
  {
    name: 'Sycamore',
    species: 'Platanus spp.',
  },
  {
    name: 'Sycamore (California)',
    species: 'Platanus racemosa',
  },
  {
    name: 'Sycamore (Arizona)',
    species: 'Platanus wrighitii',
  },
  {
    name: 'Sycamore (American)',
    species: 'Platanus occidentalis',
  },
  {
    name: 'Common tansy',
    species: 'Tanacetum vulgare',
  },
  {
    name: 'White tansy',
    species: 'Achillea ptarmica',
  },
  {
    name: 'Wild tansy',
    species: 'Ambrosia artemisiifolia',
  },
  {
    name: 'Tea',
    species: 'Camellia sinensis',
  },
  {
    name: 'Appalachian tea',
    species: 'Ilex glabra',
  },
  {
    name: 'Thimbleberry',
    species: 'Rubus occidentalis',
  },
  {
    name: 'Thimbleweed',
    species: 'Rudbeckia laciniata',
  },
  {
    name: 'Thousand-leaf',
    species: 'Achillea millefolium',
  },
  {
    name: 'Thousand-seal',
    species: 'Achillea millefolium',
  },
  {
    name: 'Tassel weed',
    species: 'Ambrosia artemisiifolia',
  },
  {
    name: 'Thistle',
    species: '(Several genera)',
  },
  {
    name: 'Annual sow thistle',
    species: 'Sonchus oleraceus',
  },
  {
    name: 'California thistle',
    species: 'Cirsium arvense',
  },
  {
    name: 'Canada thistle',
    species: 'Cirsium arvense',
  },
  {
    name: 'Corn thistle',
    species: 'Cirsium arvense',
  },
  {
    name: 'Corn sow thistle',
    species: 'Sonchus arvensis',
  },
  {
    name: 'Creeping thistle',
    species: 'Cirsium arvense',
  },
  {
    name: 'Cursed thistle',
    species: 'Cirsium arvense',
  },
  {
    name: 'Field sow thistle',
    species: 'Sonchus arvensis',
  },
  {
    name: 'Green thistle',
    species: 'Cirsium arvense',
  },
  {
    name: 'Hard thistle',
    species: 'Cirsium arvense',
  },
  {
    name: "Hare's thistle",
    species: 'Sonchus oleraceus',
  },
  {
    name: 'Milk thistle',
    species: 'Sonchus oleraceus',
  },
  {
    name: 'Nodding thistle',
    species: 'Carduus nutans L.',
  },
  {
    name: 'Perennial thistle',
    species: 'Cirsium arvense',
  },
  {
    name: 'Prickly thistle',
    species: 'Cirsium arvense',
  },
  {
    name: 'Sharp-fringed sow Thistle',
    species: 'Sonchus asper',
  },
  {
    name: 'Small-flowered Thistle',
    species: 'Cirsium arvense',
  },
  {
    name: 'Spiny sow thistle',
    species: 'Sonchus asper',
  },
  {
    name: 'Spiny-leaved sow Thistle',
    species: 'Sonchus asper',
  },
  {
    name: 'Swine thistle',
    species: 'Sonchus arvensis',
  },
  {
    name: 'Tree sow thistle',
    species: 'Sonchus arvensis',
  },
  {
    name: 'Way thistle',
    species: 'Cirsium arvense',
  },
  {
    name: 'Thyme',
    species: 'Thymus, specifically Thymus vulgaris',
  },
  {
    name: 'Tickleweed',
    species: 'Veratrum viride',
  },
  {
    name: 'Tobacco plant',
    species: 'Nicotiana',
  },
  {
    name: 'Tomato',
    species: 'Solanum lycopersicum',
  },
  {
    name: 'Toothwort',
    species: 'Cardamine concatenata',
  },
  {
    name: 'Cutleaf toothwort',
    species: 'Cardamine concatenata',
  },
  {
    name: 'Purple-flowered Toothwort',
    species: 'Cardamine concatenata',
  },
  {
    name: 'Touch-me-not',
    species: 'Impatiens capensis, Impatiens pallida, Mimosa pudica, Cardamine hirsuta',
  },
  {
    name: "Traveller's joy",
    species: 'Clematis virginiana',
  },
  {
    name: 'Tread-softly',
    species: 'Solanum carolinense',
  },
  {
    name: 'Tree tobacco',
    species: 'Nicotiana glauca',
  },
  {
    name: 'Trillium',
    species: 'Trillium spp.',
  },
  {
    name: 'Western trillium',
    species: 'Trillium ovatum',
  },
  {
    name: 'Western wake robin',
    species: 'Trillium ovatum',
  },
  {
    name: 'White trillium',
    species: 'Trillium grandiflorum',
  },
  {
    name: 'Tuber-root',
    species: 'Asclepias tuberosa',
  },
  {
    name: 'Tulip',
    species: 'Tulipa',
  },
  {
    name: 'Tulsi',
    species: 'Ocimum santalum',
  },
  {
    name: 'Vanilla orchid',
    species: 'Vanilla',
  },
  {
    name: 'Viburnum',
    species: 'Viburnum',
  },
  {
    name: 'Blackhaw viburnum',
    species: 'Viburnum prunifolium',
  },
  {
    name: 'Leatherleaf viburnum',
    species: 'Viburnum rhytidophyllum',
  },
  {
    name: 'Violet',
    species: '(several genera)',
  },
  {
    name: 'African violet',
    species: 'Saintpaulia species',
  },
  {
    name: 'Damask violet',
    species: 'Hesperis matronalis',
  },
  {
    name: "Dame's violet",
    species: 'Hesperis matronalis',
  },
  {
    name: "Dog's-tooth-violet or dogtooth violet",
    species: 'Erythronium dens-canis',
  },
  {
    name: 'Violet bloom',
    species: 'Solanum dulcamara',
  },
  {
    name: "Virgin's bower",
    species: 'Clematis virginiana',
  },
  {
    name: "Virginia virgin's bower",
    species: 'Clematis virginiana',
  },
  {
    name: 'Walnut (California walnut)',
    species: 'Juglans californica',
  },
  {
    name: 'Walnut',
    species: 'Juglans sp.',
  },
  {
    name: 'Waybread',
    species: 'Plantago major',
  },
  {
    name: 'Western redbud',
    species: 'Cercis occidentalis',
  },
  {
    name: 'Wheat',
    species: 'Triticum spp.',
  },
  {
    name: "White man's foot",
    species: 'Plantago major',
  },
  {
    name: 'White-root',
    species: 'Asclepias tuberosa',
  },
  {
    name: 'Wild cotton',
    species: 'Apocynum cannabinum, Asclepias syriaca',
  },
  {
    name: 'Wild hops',
    species: 'Clematis virginiana',
  },
  {
    name: 'Willow',
    species: 'Salix',
  },
  {
    name: 'Coyote willow',
    species: 'Salix exigua',
  },
  {
    name: 'Goodding willow',
    species: 'Salix gooddingii',
  },
  {
    name: 'Red willow',
    species: 'Cornus amomum',
  },
  {
    name: 'Rose willow',
    species: 'Cornus amomum',
  },
  {
    name: 'Windroot',
    species: 'Asclepias tuberosa',
  },
  {
    name: 'Wineberry',
    species: 'Rubus phoenicolasius',
  },
  {
    name: 'Winterberry',
    species: 'Ilex verticillata',
  },
  {
    name: 'American winterberry',
    species: 'Ilex verticillata',
  },
  {
    name: 'Evergreen winterberry',
    species: 'Ilex glabra',
  },
  {
    name: 'Virginia winterberry',
    species: 'Ilex verticillata',
  },
  {
    name: 'Wintercress',
    species: 'Barbarea vulgaris',
  },
  {
    name: 'Early wintercress',
    species: 'Barbarea verna',
  },
  {
    name: 'Woodbine',
    species: 'Clematis virginiana',
  },
  {
    name: 'Roman wormwood',
    species: 'Ambrosia artemisiifolia, Corydalis sempervirens',
  },
  {
    name: 'Wound rocket',
    species: 'Barbarea vulgaris',
  },
  {
    name: 'Yarrow',
    species: 'Achillea',
  },
  {
    name: 'Common yarrow',
    species: 'Achillea millefolium',
  },
  {
    name: 'Fernleaf yarrow',
    species: 'Achillea filipendulina',
  },
  {
    name: 'Sneezewort yarrow',
    species: 'Achillea ptarmica',
  },
  {
    name: 'Woolly yarrow',
    species: 'Achillea tomentosa',
  },
  {
    name: 'Yellow fieldcress',
    species: 'Rorippa sylvestris',
  },
  {
    name: 'Yellowwood',
    species: 'Cladrastis lutea, Maclura pomifera',
  },
  {
    name: 'Yellow coneflower',
    species: 'Echinacea paradoxa',
  },
  {
    name: 'Zedoary',
    species: 'Curcuma zedoaria',
  },
];

const rndAdjective = () => {
  let i = Math.floor(Math.random() * adjectives.length);
  return adjectives[i];
};

const rndSpecies = () => {
  const plantsLength = plants.length;
  const i = Math.floor(Math.random() * plantsLength);
  const name = plants[i].name;
  return name.replace('-', ' ').replace(/[^a-zA-Z|\s]/g, '');
};

const capWord = (w: string) => {
  const [firstLetter, ...rest] = w;
  return `${firstLetter.toLocaleUpperCase()}${rest.join('')}`.trim();
};

const rndName = (): string => {
  const adj = rndAdjective();
  const capAdj = capWord(adj);
  let result = capAdj;

  const spe = rndSpecies();
  const splitted = spe.split(' ');
  splitted.forEach((e) => {
    const trimmed = e.trim();
    if (trimmed.length > 0) {
      let cap = capWord(e);
      result = `${result} ${cap}`;
    }
  });
  return result;
};

const rndID = (): string => {
  const name = rndName();
  const lc = name.toLocaleLowerCase();
  return lc.replaceAll(/\s+/g, '-');
};

export const randomName = rndName;
export const randomID = rndID;
